# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_QPA_PLATFORM: "offscreen"

jobs:

  build-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

  run-app:
    needs: build-env
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: apt install
      run: sudo apt install -y libopengl0 -y
    - name: run main.py
      run: timeout 20 python ./main.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
    - name: timeout
      run: timeout 1 python ./main.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

  lint-app:
    needs: run-app
    runs-on: ubuntu-latest
    steps:
    - name: install flake8
      run: |
        pip install flake8 pytest
    - name: lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  format-app:
    needs: lint-app
    runs-on: ubuntu-latest
    steps:
    - name: black Formatter
      uses: piotrpawlaczek/python-blacken@release/stable
      with:
        line-length: '120'
        path: '.'
        sanity-check: 'safe'
        only-check: 'no'
